synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:964564:
  appc.background(230);
} //_CODE_:window1:964564:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window1:964564:
  appc.background(230);
} //_CODE_:window1:964564:

synchronized public void win_draw3(PApplet appc, GWinData data) { //_CODE_:window1:964564:
  appc.background(230);
} //_CODE_:window1:964564:

public void button_resign(GButton source, GEvent event) { //_CODE_:button3:403542:
  server.button_resign();
} //_CODE_:button3:403542:

public void button_connect(GButton source, GEvent event) { 
  server.button_connect();
} 

public void button_yes(GButton source, GEvent event) { 
  if(server.inPromt != null)
  {
    server.inPromt.connection.button_yes();
  }
} 

public void button_no(GButton source, GEvent event) { 
  if(server.inPromt != null)
  {
    server.inPromt.connection.button_no();
  }
} 

public void name_change(GTextField source, GEvent event) { 
  if(event == GEvent.ENTERED || event == GEvent.LOST_FOCUS)
  {
    server.game.name_change();
  } 
} 



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Game");
  
  window0 = GWindow.getWindow(this, "Main Menu", 0, 0, 301, 301, JAVA2D);
  window0.noLoop();
  window0.setActionOnClose(G4P.KEEP_OPEN);
  window0.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window0, 99, 5, 100, 35);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Main Menu");
  label1.setTextBold();
  label1.setOpaque(false);
  textarea1 = new GTextArea(window0, 9, 74, 117, 215, G4P.SCROLLBARS_VERTICAL_ONLY | G4P.SCROLLBARS_AUTOHIDE);
  textarea1.setOpaque(true);
  label2 = new GLabel(window0, 5, 45, 120, 23);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Scanning Hosts...");
  label2.setTextBold();
  label2.setOpaque(false);
  textfield1 = new GTextField(window0, 134, 74, 145, 28, G4P.SCROLLBARS_NONE);
  textfield1.setPromptText("Enter host:");
  textfield1.setOpaque(true);
  button1 = new GButton(window0, 166, 168, 73, 18);
  button1.setText("Connect");
  button1.setTextBold();
  button1.addEventHandler(this, "button_connect");
  textfield2 = new GTextField(window0, 136, 118, 143, 28, G4P.SCROLLBARS_NONE);
  textfield2.setPromptText("Enter name:");
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "name_change");
  label3 = new GLabel(window0, 178, 275, 119, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Copyright@VGU");
  label3.setTextBold();
  label3.setOpaque(false);
  window0.loop();
  
  window1 = GWindow.getWindow(this, "Challenge popup", 0, 0, 240, 160, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.CLOSE_WINDOW);
  window1.addDrawHandler(this, "win_draw2");
  label4 = new GLabel(window1, 27, 12, 164, 30);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setTextBold();
  label4.setOpaque(false);
  button2 = new GButton(window1, 18, 60, 80, 30);
  button2.setText("Yes");
  button2.setTextBold();
  button2.addEventHandler(this, "button_yes");
  button3 = new GButton(window1, 128, 60, 80, 30);
  button3.setText("No");
  button3.setTextBold();
  button3.addEventHandler(this, "button_no");
  window1.loop();
  
  window2 = GWindow.getWindow(this, "Match stats", 0, 0, 240, 60, JAVA2D);
  window2.noLoop();
  window2.setActionOnClose(G4P.CLOSE_WINDOW);
  window2.addDrawHandler(this, "win_draw3");
  label5 = new GLabel(window2, 20, 10, 100, 17);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Player 1: 0");
  label5.setTextBold();
  label5.setOpaque(false);
  label6 = new GLabel(window2, 20, 30, 100, 17);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Player 2: 0");
  label6.setTextBold();
  label6.setOpaque(false);
  button4 = new GButton(window2, 150, 30, 80, 30);
  button4.setText("Resign");
  button4.addEventHandler(this, "button_resign");
  window2.loop();
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GTextArea textarea1; 
GLabel label2; 
GTextField textfield1; 
GButton button1; 
GTextField textfield2; 
GLabel label3; 
GWindow window0;
GWindow window1;
GWindow window2;
GLabel label4; 
GLabel label5;
GLabel label6; 
GButton button2; 
GButton button3; 
GButton button4; 
